name: Sync Directory
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gpu-mode/triton-tutorials
          path: gpu-mode/triton-tutorials
      - uses: actions/checkout@v3
        with:
          repository: svekars/doc-test
          path: doc-test
          token: ${{ secrets.PAT_TOKEN }}
      - run: |
          mkdir -p doc-test/triton-tutorials
          find gpu-mode/triton-tutorials -name "*.py" -exec cp --parents {} doc-test/triton-tutorials \; 
          cd doc-test
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Sync directory from source repo" || echo "No changes to commit"
          git push
